### ISSUE TITLE
Error: The API Key provided is not valid

### ISSUE THREAD

**Issue by Brandnewson** [JBooker10/node-iex-cloud#30]
``I'm currently attempting a nodeJS project using commonJS modules. Whenever I try to run my server it gives me the following error:

Error: The API key provided is not valid.
    at IEXRequest.<anonymous> (D:\Coding\iib\node_modules\node-iex-cloud\lib\request.js:128:31)
    at step (D:\Coding\iib\node_modules\node-iex-cloud\lib\request.js:32:23)
    at Object.next (D:\Coding\iib\node_modules\node-iex-cloud\lib\request.js:13:53)
    at fulfilled (D:\Coding\iib\node_modules\node-iex-cloud\lib\request.js:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
   This is the code I used to install `node-iex-cloud

```
`const { IEXCloudClient } = require("node-iex-cloud");
const fetch = require("node-fetch");

const iex_module = new IEXCloudClient(fetch, {
  sandbox: true,
  publishable: "pk_API_KEY",
  version: "stable"
});`
```

**Comment by Brandnewson** [comment]
Running the secret key also gives me the same error, so I'm unsure of how to move forward from here.

**Comment by JBooker10** [comment]
@Brandnewson Seems like this is not a problem with the client. This error is being returned directly from iex. Make sure you are using the `PUBLISHABLE` token instead of the secret.

**Comment by Brandnewson** [comment]
okay thanks! I'll check what's the issue with them.
